### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by chingc** [star-micronics/cloudprnt-sdk#6] opened 2022-06-22 21:38 UTC
Running CPUtil under Ubuntu 22.04 LTS (Jammy) results in a libssl error.

I am running v110 downloaded from: https://www.star-m.jp/products/s_print/CloudPRNTSDK/Documentation/en/articles/cputil/cputil_getting.html

Search around and found this explanation which I hope is helpful:

> The core issue is that Linux uses .NET core 3.1. However, Ubuntu 22.04 LTS ships with libssl3 which is only supported by .NET 6. Unfortunately, Microsoft has confirmed on GitHub they won’t be adapting .NET core 3.1 to support libssl3.

**Comment by gare-bear** [comment] 2022-12-20 18:07
@bandit-ibayashi @Lozrus any ideas on how we can solve this? 
If we had a build that targetted .NET6, would that be enough?

**Comment by Lozrus** [comment] 2022-12-21 12:24
@gare-bear Yes, this is exactly the issue, the stand-alone binaries are built with .Net Core 3.1 LTS, which predates, and doesn't support Ubuntu 22.04. We have the source available, so users can rebuild for their platform, but it is worth considering an update to the binaries, especially since Ubuntu 22.04 is an LTS.

@bandit-ibayashi  Can SMJ share updated binaries, built against .Net 6? Or perhaps provide a framework independent option so that users can install the runtime separately?

**Comment by gare-bear** [comment] 2022-12-21 14:17
@chingc until we provide newer pre-built binaries, please try building from source. 
Instructions can be found [here](https://www.star-m.jp/products/s_print/CloudPRNTSDK/Documentation/en/articles/cputil/cputil_getting.html#building-from-source).

Source code is already available under this repo.

**Comment by bandit-ibayashi** [comment] 2023-01-18 08:27
> @bandit-ibayashi Can SMJ share updated binaries, built against .Net 6? Or perhaps provide a framework independent option so that users can install the runtime separately?

@Lozrus  Sorry for my late reply.
We have already updated binaries of cputil supporting .Net 6 as version 1.1.2. So it will be available if it is downloaded again. Just to be sure, I ran it on Ubuntu 22.04 and confirmed that there were no problems.

**Comment by gare-bear** [comment] 2023-01-19 03:52
@chingc latest version built on .NET 6 can be found here
https://star-m.jp/products/s_print/CloudPRNTSDK/cputil/cputil-linux-x64_v112.tar.gz

closing this issue.

**Closed as completed by gare-bear** 2023-01-19 03:52 UTC
